---
# save current node to "{{ node_dict }}"
- name: get node_dict
  include: var_lookup.yml
  vars:
      var_file: "{{ node.key }}"
      partial_path: topology/nodes

- include: tasks/netip_natted.yml
  when: "not topology_node.external_network.bridged|default(False)"

- include: tasks/netip_bridged.yml
  when: "topology_node.external_network.bridged|default(False)"
